### ISSUE TITLE
flatex.py fails: TypeError: _download_current_pdfs() missing 1 required positional argument: 'tld'

### ISSUE THREAD

**Issue by satheras** [pspeter/statement-dl#3]
The lines  197/203 of  flatex.py should be the same:

`   _download_current_pdfs(driver, download_path, dest, all_files, keep_filenames, tld)`

instead of
`   _download_current_pdfs(driver, download_path, dest, all_files, keep_filenames)`

So The parameter ", tld" is missing. This leads to the error:

```
C:\Users\XXXX>statement_dl flatex D:\Documents\ --all-files -g C:\Users\XXXX\geckodriver.exe
Please login in the browser
Downloading files to D:\Documents
More than 100 files, paging through results
Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\Scripts\statement_dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\statement_dl\__init__.py", line 92, in main
    args.func(args)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\statement_dl\flatex.py", line 42, in download_documents_from_args
    download_documents(
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\statement_dl\flatex.py", line 93, in download_documents
    _download_pdfs(
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\statement_dl\flatex.py", line 197, in _download_pdfs
    _download_current_pdfs(driver, download_path, dest, all_files, keep_filenames)
TypeError: _download_current_pdfs() missing 1 required positional argument: 'tld'
```

and the script would not work.

Thanks for the great work!

**Comment by pspeter** [comment]
Thanks for your report! You are right of course, I fixed it in the latest version :)
